version: '3'

services:
  db:
    image: postgres
   environment:
      POSTGRES_PASSWORD: dockeando
      POSTGRES_USER: dockeando
      POSTGRES_DB: dockeando    
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:1010
    volumes:
      - .:/dockeando
    ports:
      - "1010:1010"
    depends_on:
      - db