version: '3'
services:

    db:
      restart: always  
      image: postgres
      container_name: dbdockerando01
      environment:
        POSTGRES_PASSWORD: dockeando
        POSTGRES_USER: dockeando
        POSTGRES_DB: dockeando    
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
      restart: always
      container_name: nginxdockerandod01
      build: ./nginx      
      volumes:
        - web_data:/dockeando        
        - ./log:/var/log/nginx              
      ports:
        - "8080:80" 
      depends_on:
        - web

    web:
      restart: always  
      build: .
      container_name: webdockerando01
      command: uwsgi --ini uwsgi.ini         
      volumes:
        - web_data:/dockeando        
      ports:
        - "8000"
      depends_on:
        - db
      
volumes:
    web_data:
    pgdata:

